<?php

namespace Kinomitech\ConfmgrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfmgrFullPaperFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfmgrFullPaperFilesRepository extends EntityRepository
{
}
